config/routes.rb
Rails.application.routes.draw do


  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :admins do
    collection do
      get 'index'
      get 'allcontent'
    end	
  end

  resources :posts do
    collection do
      get 'recent'
      get 'showpost'
      get 'allcontent'
      get 'admin'
    end	
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'

end

app/models/admin.rb
class Admin < ApplicationRecord

validates(:username, presence: true, length: {maximun: 20, minimum: 2},uniqueness: true)
EMAILFORMAT = /\A[\w+\-]+@[a-z\d\-.]+\.[a-z]+\z/i
validates(:email, presence: true, length: {maximun: 50, minimum: 5}, format: {with: EMAILFORMAT}, uniqueness: {case_sensitive: false})
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(admins_params)
    if @admin.save
        session[:admin_id] = @admin.id
	redirect_to @admin
    else
      render 'new'
    end
  end

  def allcontent
    @admin = Admin.all
  end

  def index
    @admin = Admin.all
  end

  def show
    @admin = Admin.find(params[:id])
  end
  
  def admins_params
    params.require(:admin).permit(:username, :email)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end
  
  # GET /posts/allcontent
  def allcontent
    @posts = Post.all
  end

  # GET /posts/admin
  def admin
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end
  # GET /posts/recent
  def recent
    @posts = Post.all    
  end
  # GET /posts/1/edit
  def edit
  end
  # GET /posts/showpost
  def showpost
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @admin = Admin.find(session[:admin_id])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @admin = Admin.find_by_id(params[:session][:id])
    if @admin
      session[:admin_id] = @admin.id
      session[:admin_username] = @admin.username
      session[:admin_email] = @admin.email        
      redirect_to @admin
    else
      render 'new'
    end
  end

  def destroy
    session.delete(:admin_id)
    render 'new'
  end

  def saved
    session[:admin_id] = @admin.id
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/allcontent.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>userid</th>
      <th>username</th>
      <th>email</th>
    </tr>
  </thead>

  <tbody>
    <% @admin.each do |admin| %>
      <tr>
	<td><%= admin.id %></td>
        <td><%= admin.username %></td>
        <td><%= admin.email %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>
<%= link_to 'Back', admins_path %>

<br>

app/views/admins/index.html.erb
<h1> Admin Infor Page</h1>

<a href="/admins/new"> create new admin </a>
<br>
<a href="/admins/allcontent"> show all admins </a>
<br>
<%= link_to 'Back', posts_path %>

app/views/admins/new.html.erb
<h1> Sign Up User</h1>

<%= form_for(@admin) do |form| %>

    <%= form.label :email %>
    <%= form.text_field :email %>

    <%= form.label :username %>
    <%= form.text_field :username %>

    <%= form.submit %>
<% end %>

app/views/admins/show.html.erb
<h1> Admin Infor Page</h1>
username: <%= @admin.username %>
<br>
email: <%= @admin.email %>
<br>
<%= link_to 'Back', admins_path %>
<br>
<%= link_to "Log Out", logout_path, method:"delete" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weibo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/admin.html.erb
<p id="notice"><%= notice %></p>

<h1>Edit Posts</h1>

<%= link_to 'Add New Post', new_post_path %>
<br>
<hr color="black">
<table>
  <thead>
    <tr>
      <th>Current Content List</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr color="black">
<br>
<%= link_to 'Back', posts_path %>

<br>

app/views/posts/allcontent.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Content ID</th>
      <th>Content List</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
	<td><%= post.id %></td>
        <td><%= post.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', posts_path %>

<br>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome to myPost</h1>
<br>

<a href = "/posts/allcontent"> Show All Posts</a>
<br>
<a href = "/posts/recent"> Show Recent Posts</a>
<br>
<a href = "/posts/admin"> Edit Current Posts</a>
<br>
<a href = "/admins"> Admin Account</a>
<br>
<a href = "/login"> Log In</a>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/recent.html.erb
<p id="notice"><%= notice %></p>

<h1>Recent Posts</h1>

<table>
  <thead>
    <tr>
      <th>Post ID</th>
      <th>Content List</th>

    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>      
      <tr>
        <td><%= post.id %></td>
        <td><%= post.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', posts_path %>

<br>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<br>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/showpost.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= link_to "posts list",posts_path %>
</p>